### ISSUE TITLE
CSL Elite Pedals

### ISSUE THREAD

**Issue by qdlmcfresh** [gotzl/hid-fanatecff#18]
Hi, id like to use this with [CSL Elite Pedals](https://fanatec.com/eu-en/pedals/csl-elite-pedals). Ultimatly i need to read brake and gas values from the pedals. I have a [Clubsport-USB-Adapter](https://fanatec.com/eu-en/accessories/pedal-accessories/clubsport-usb-adapter) to connect it to my PC. 

The Pedals show up as:
```
Bus 003 Device 003: ID 0eb7:1a95 Endor AG ClubSport USB Pedal
```
So i changed the following in the driver:
https://github.com/qdlmcfresh/hid-fanatecff/commit/cf581c390bcd203556621fb11cea72a1dafc5910
dmesg output:
```
[ 2041.931873] input: FANATEC ClubSport USB Pedal as /devices/pci0000:00/0000:00:15.0/0000:03:00.0/usb3/3-2/3-2:1.0/0003:0EB7:1A95.0004/input/input11
[ 2041.932016] ftec_csl_elite 0003:0EB7:1A95.0004: input,hidraw1: USB HID v1.11 Joystick [FANATEC ClubSport USB Pedal] on usb-0000:03:00.0-2/input0
[ 2041.932018] /home/qdl/Bectec/fork_hid_fanatec/hid-ftec.c:  ... 0 1 1 16
               0 255 0 0

[ 2041.932020] ftec_csl_elite 0003:0EB7:1A95.0004: not enough values in HID_OUTPUT_REPORT 0 field 0
[ 2041.932021] ftec_csl_elite 0003:0EB7:1A95.0004: hw init failed
[ 2041.968830] ftec_csl_elite: probe of 0003:0EB7:1A95.0004 failed with error -1
```

**Comment by gotzl** [comment]
Hi,
you don't need this driver for the pedals. Reading throttle/brake values just works with the default HID driver.
The only addition my driver brings would be if you had the brake-pedal with load-cell. Then, the driver allows to adjust the load cell sensitivity.

That said, I think the issue your seeing with my driver (`not enough values ..`) could be related to what we've seen in #16.

**Comment by qdlmcfresh** [comment]
Thanks came to the same conclusion after testing with jstest. Thanks anyways :+1: :smile:
