### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by knfrmity** [gotzl/hid-fanatecff#68]
Since pulling the latest version I have seen various make issues which seem to have started with the changes made with #44. Rolling back to the commit previous to merging that PR (9c186b5) solves the issue.

The error: 
```
../hid-fanatecff/hid-ftecff.c:345:9: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  345 |         for(int valueIndex = 4; valueIndex <= 6 && bufIndex < count; valueIndex++) {
      |         ^~~
.../hid-fanatecff/hid-ftecff.c:345:9: note: use option ‘-std=c99’, ‘-std=gnu99’, ‘-std=c11’ or ‘-std=gnu11’ to compile your code
make[2]: *** [scripts/Makefile.build:297: .../hid-fanatecff/hid-ftecff.o] Error 1
make[1]: *** [Makefile:1909: .../hid-fanatecff] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-91-generic'
make: *** [Makefile:8: default] Error 2
```

There are a few warnings as well which may not be critical.

`.../hid-fanatecff/hid-ftecff.c:343:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]`

`.../hid-fanatecff/hid-ftecff.c:1087:17: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]`

Since I can roll back to a working config it's not a big problem, but maybe some others have the same issue. I am using Linux Mint in case that's relevant.

**Comment by gotzl** [comment]
Thanks for reporting. Does it compile with the latest fix?

**Comment by knfrmity** [comment]
Yes, it compiles as expected now. Thanks!
