### ISSUE TITLE
ClubSport Steering Wheel F1® Esports V2

### ISSUE THREAD

**Issue by salsadinner** [gotzl/hid-fanatecff#69]
Hi!
This is my first racing wheel setup, so please excuse my ignorance if any.

I am trying to setup the [ClubSport Steering Wheel F1® Esports V2](https://fanatec.com/eu-en/steering-wheels/clubsport-steering-wheel-f1-esports-v2) with CSL DD1 on Arch linux. Everything is detected, but I see that the steering does not work as expected. I need two complete rotations in either direction during calibration to hit -100 or +100.

How do I go about fixing this ?

**Comment by gotzl** [comment]
Which game is this? 
Generally you can adjust the range of the wheel with the SEN setting in the tuning-menu directly on the wheel. This is probably set to 'AUTO'... Try if it works better for you to set it eg to 108 (with would be 1080 degrees).

**Comment by salsadinner** [comment]
Thank you so much, that fixed it!
