### ISSUE TITLE
Automobilista 2 crash at startup

### ISSUE THREAD

**Issue by sigonze** [gotzl/hid-fanatecff#99]
Hi,
I notice that AMS2 is tagged as supported but I have a crash at the startup of the game (just after the first logo). 
After trying multiple combinations, I discovered that when my fanatec wheel is OFF (CSL DD), I have no issue. But at the moment I power it ON, the game just crash. 
I tried multiple proton (8, 9, experimental, GE) nothing change. 
I also did a fresh install. 
So if you have any clue I am very interested. 
Thanks.

**Comment by gotzl** [comment]
Hi,
this is a known issue, see #67. The workaround is to start the game once with proton6, then switch to a more recent proton version.

**Comment by sigonze** [comment]
Sorry did not see the other issue.
I just confirm it works. Thank you for your help. :+1:

**Comment by gotzl** [comment]
Glad it works now, no need to appologize!
